name: Docker Build & Push

on:
  workflow_dispatch:
    inputs:
      image_choice:
        description: 'Choose which Docker image to build and push'
        required: true
        type: choice
        options:
          - InitialBlue
          - FinalGreen

# on:
#     push:
#         branches:
#             - dev


jobs:
    Docker-InitialBlue:
        runs-on: ubuntu-latest
        if: ${{ inputs.image_choice == 'InitialBlue' }}
        defaults:
            run:
                working-directory: "./app/initialblue/"
        permissions:
            security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
            id-token: write   # This is required for requesting the JWT

        steps:
            - name: Checkout
              uses: actions/checkout@v4


            - name: Login to AWS
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: arn:aws:iam::677276074604:role/github-cicd-role
                role-session-name: github-actions-session
                aws-region: eu-west-2

            - name: Login to AWS ECR
              uses: aws-actions/amazon-ecr-login@v2

            - name: Build
              run: |
                docker build -t url-shortener:initialblue .
                docker tag url-shortener:initialblue 677276074604.dkr.ecr.eu-west-2.amazonaws.com/url-shortener:initialblue

            - name: Trivy Scan
              uses: aquasecurity/trivy-action@master
              with:
                image-ref: url-shortener:initialblue
                severity: 'CRITICAL,HIGH'
                format: 'sarif'
                output: 'trivy-results-Docker.sarif'
                exit-code: 0   # 1 means that any vulnerabilities found, that meet the severity criteria, will raise an error and will not allow the pipeline code to continue. 0 would allow the pipeline code to continue no matter the vulnerability.
      
            - name: Upload Trivy scan results to GitHub Security tab
              uses: github/codeql-action/upload-sarif@v3
              with:
                sarif_file: 'trivy-results-Docker.sarif'
                wait-for-processing: true

            - name: Push to ECR
              run: |
                docker push 677276074604.dkr.ecr.eu-west-2.amazonaws.com/url-shortener:initialblue


    Docker-FinalGreen:
        runs-on: ubuntu-latest
        if: ${{ inputs.image_choice == 'FinalGreen' }}
        defaults:
            run:
                working-directory: "./app/finalgreen/"
        permissions:
            security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
            id-token: write   # This is required for requesting the JWT

        steps:
            - name: Checkout
              uses: actions/checkout@v4


            - name: Login to AWS
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: arn:aws:iam::677276074604:role/github-cicd-role
                role-session-name: github-actions-session
                aws-region: eu-west-2

            - name: Login to AWS ECR
              uses: aws-actions/amazon-ecr-login@v2

            - name: Build
              run: |
                docker build -t url-shortener:finalgreen .
                docker tag url-shortener:finalgreen 677276074604.dkr.ecr.eu-west-2.amazonaws.com/url-shortener:finalgreen

            - name: Trivy Scan
              uses: aquasecurity/trivy-action@master
              with:
                image-ref: url-shortener:finalgreen
                severity: 'CRITICAL,HIGH'
                format: 'sarif'
                output: 'trivy-results-Docker.sarif'
                exit-code: 0   # 1 means that any vulnerabilities found, that meet the severity criteria, will raise an error and will not allow the pipeline code to continue. 0 would allow the pipeline code to continue no matter the vulnerability.
      
            - name: Upload Trivy scan results to GitHub Security tab
              uses: github/codeql-action/upload-sarif@v3
              with:
                sarif_file: 'trivy-results-Docker.sarif'
                wait-for-processing: true

            - name: Push to ECR
              run: |
                docker push 677276074604.dkr.ecr.eu-west-2.amazonaws.com/url-shortener:finalgreen